### ISSUE TITLE
Missing hover tooltip on the "Image Diffs"

### ISSUE THREAD

**Issue by elashahar01** [Samsung/qaboard#2]
**Describe the bug**
When hovering over the diff image, the x-y coordinates and the rgb values of the pixel in the  images being compared are not updated.

**To Reproduce**
1. Click on the Visualizations tab
2. Click on the Image Diff button
3. Hover over a diff image
4. See error - x-y and rgb values are "stuck"

**Expected behavior**
x-y coordinates and rgb values of the images being compared should change and consist of correct values

**Desktop**
 - OS: Windows 10
 - Browser: chrome

**Comment by arthur-flam** [comment]
Hi Ela,
Thanks for noticing it!
I fixed the issue and will soon push/merge the patch.
