### ISSUE TITLE
uncommon failure while running a CI

### ISSUE THREAD

**Issue by amitkadmon** [Samsung/qaboard#5]
**Describe the bug**
failing to run in ci board, getting the following error:
Error signal: -11 SIGSEGV
was adviced by Arthur that another user has the same issue.

**To Reproduce**
run my ci:
https://qa/CDE-Users/HW_ALG/CIS/tests/products/HM2/commit/33f78fa151505a4b26caf6f4d80104dee0f492af?batch=Full_Mode&reference=aa8a6a20fe0b4e43b0276f6a2934a76d7d8850dc&selected_views=logs&filter=
![image](https://user-images.githubusercontent.com/62544013/77305810-5bc02200-6cff-11ea-9eb3-26ae61c8d6f6.png)

**Comment by arthur-flam** [comment]
Hi Amit,

Here the failure is not related to QA-Board, it's a segfault of the CDE application.

It may be related to the shared filesystem issue this morning, it was full. Ela showed me a corrupted, truncated binary... Now that binary wouldn't execute at all. Here it does, so I suggest running it under `gdb` and seeing what happens. We should take that discussion *offline*.

When I suggested creating an issue, it was more about the nice feature you suggested: displaying announcements in the application, e.g. to warn about scheduled maintenance, or issues like the shared filesystem being down and causing failures _everywhere_.

**Comment by amitkadmon** [comment]
Hi Arthur
Thanks for the feedback, I must have misunderstood you,
I will add the suggestion there aswell

Thanks
Amit

**Comment by arthur-flam** [comment]
Yes, I'll appreciate if you can open a different issue for the feature, I'll close this one.

So indeed, in the end, it was related to truncated binaries, with different errors depending on the side that's left 😕 Everything month we learn a new NFS failure mode 🙌
